import * as common from './common'

let host = ''
let storeId = '/bazaar'
let url = window.location.pathname
if (url[url.length - 1] == '/'){
  url = url.substring(0,url.length - 1)
}
if (url.length > 1){
  storeId = url
  storeId != '/bazaar' ? common.setCookie('sc',storeId,10) : ''
  if (sessionStorage.getItem('storeId')){
    storeId = sessionStorage.getItem('storeId')
  }else {
    sessionStorage.setItem('storeId',storeId)
  }
}
if (process.env.NODE_ENV !== 'production'){
  host = 'https://dieku-server.sunnymum.com' + storeId
}else {
  if (process.env.type == 'test'){
    host = 'https://dieku-server.sunnymum.com' + storeId
  }else {
    host = 'https://api.dearcoo.com' + storeId
  }
}


//请求的所有url地址
export const URL_GET_LOGIN_CODE = host + '/api/u/auth/login/code/get'
export const URL_GET_LOGIN_BY_PHONE = host + '/api/u/auth/code/login'
export const URL_GET_LOGIN_BY_PASSWORD = host + '/api/u/auth/password/login'
export const URL_GET_LOGIN_OUT = host + '/api/u/auth/logout'
export const URL_SET_PAY_PASSWORD = host + '/api/u/password/pay/set'
export const URL_GET_PAY_CODE = host + '/api/u/password/pay/code/get'
export const URL_GET_PAY_VALIDATE_CODE = host + '/api/u/password/pay/code/validate'
export const URL_UPDATE_PAY = host + '/api/u/password/pay/update'
export const URL_SET_LOGIN_PASSWORD = host + '/api/u/password/login/set'
export const URL_FORGOT_PARRWORD = host + '/api/u/password/forgot/code/get'
export const URL_FORGOT_VALIDATE_CODE = host + '/api/u/password/forgot/code/validate'
export const URL_PASSWORD_FORGOT_RESET = host + '/api/u/password/forgot/reset'
export const URL_GET_SHOP_LIST = host + '/api/u/shop/index'
export const URL_MEMBER_REGISTER_INFO = host + '/api/u/member/register/info'
export const URL_MEMBER_REGISTER_CODE = host + '/api/u/member/register/code/get'
export const URL_MEMBER_REGISTER_SUBMIT = host + '/api/u/member/register/submit'
export const URL_FILE_BASE64_UPLOAD = host + '/api/u/file/base64/upload'
export const URL_FILE_FORMDATA_UPLOAD = host + '/api/u/file/upload'
export const URL_DATA_CONFIG_BIZPARAM = host + '/data/config/bizparam'
export const URL_MEMBER_ASSIST_REGISTER_INFO = host + '/api/u/member/assist/register/info'
export const URL_MEMBER_ASSIST_REGISTER_CODE = host + '/api/u/member/assist/register/code/get'
export const URL_MEMBER_ASSIST_REGISTER_SUBMIT = host + '/api/u/member/assist/register/submit'
export const URL_MEMBER_ASSIST_REGISTER_SUBMIT_SIMPLE = host + '/api/u/member/register/simple/submit'
export const URL_MEMBER_MEMBER_ASSIST_REGISTER_SUBMIT_SIMPLE = host + '/api/u/member/assist/register/simple/submit'
export const URL_DEALER_SUBMIT = host + '/api/u/dealer/submit'
export const URL_MEMBER_INFO = host + '/api/u/member/info'
export const URL_MEMBER_NICKNAME_SET = host + '/api/u/member/nickname/set'
export const URL_MEMBER_NAME_SET = host + '/api/u/member/name/set'
export const URL_MEMBER_SEX_SET = host + '/api/u/member/sex/set'
export const URL_MEMBER_BIRTHDAY_SET = host + '/api/u/member/birthday/set'
export const URL_MEMBER_AVATAR_SET = host + '/api/u/member/avatar/set'
export const URL_MEMBER_WX_NO_SET = host + '/api/u/member/wx/no/set'
export const URL_MEMBER_WX_QRCODE_SET = host + '/api/u/member/wx/qrcode/set'
export const URL_GUIDE_QRCODE_GET = host + '/api/u/guide/qrcode/get'
export const URL_MEMBER_STORE_LOGO_SET = host + '/api/u/member/store/logo/set'
export const URL_MEMBER_STORE_NAME_SET = host + '/api/u/member/store/name/set'
export const URL_MEMBER_STORE_BRIEF_SET = host + '/api/u/member/store/brief/set'
export const URL_BANKCARD_LIST = host + '/api/u/bankcard/list'
export const URL_BANKCARD_DEFAULT_SET = host + '/api/u/bankcard/default/set'
export const URL_BANKCARD_RECOGNISE = host + '/api/u/bankcard/recognise'
export const URL_BANKCARD_ADD = host + '/api/u/bankcard/add'
export const URL_BANKCARD_DEL = host + '/api/u/bankcard/del'
export const URL_BANKCARD_SUPPORT_LIST = host + '/api/u/bankcard/support/list'
export const URL_BANKCARD_DEFAULT_WIYHDRAW_GET = host + '/api/u/bankcard/default/withdraw/get'
export const URL_BANKCARD_DEFAULT_WIYHDRAW_BASIC = host + '/api/u/wallet/withdraw/basic'
export const URL_BANKCARD_DEBIT_LIST = host + '/api/u/bankcard/debit/list'
export const URL_COLLECT_LIST = host + '/api/u/collect/list'
export const URL_COLLECT_ADD = host + '/api/u/collect/add'
export const URL_COLLECT_CENCEL = host + '/api/u/collect/cancel'
export const URL_ADDRESS_LIST = host + '/api/u/address/list'
export const URL_ADDRESS_SAVE = host + '/api/u/address/save'
export const URL_ADDRESS_DEL = host + '/api/u/address/del'
export const URL_ASSIST_POSTER = host + '/api/u/assist/poster'
export const URL_ASSIST_FEEDBACK_ADD = host + '/api/u/assist/feedback/add'
export const URL_ASSIST_MSG_LIST = host + '/api/u/assist/msg/list'
export const URL_ASSIST_PEOPLE_DIRECT = host + '/api/u/assist/people/direct'
export const URL_GOODS_CATEGORY_LIST = host + '/api/u/shop/goods/category/list'
export const URL_GET_SHOP_GOODS_LIST = host + '/api/u/shop/goods/list'
export const URL_GOODS_GIFT_LIST = host + '/api/u/shop/gift/package/detail'
export const URL_SHOP_GOODS_DETAIL = host + '/api/u/shop/goods/detail'
export const URL_SHOP_MARKET_PACKAGE_LIST = host + '/api/u/shop/market/package/list'
export const URL_PACKAGE_CATEGORY_LIST = host + '/api/u/shop/market/package/detail'
export const URL_CART_LIST = host + '/api/u/cart/list'
export const URL_CART_PLUS = host + '/api/u/cart/plus'
export const URL_CART_REDUCE = host + '/api/u/cart/reduce'
export const URL_CART_REMOVE = host + '/api/u/cart/remove'
export const URL_CART_INVALID_CLEAR = host + '/api/u/cart/invalid/clear'
export const URL_PAY_CALCULATE = host + '/api/u/pay/calculate'
export const URL_PAY_ORDER = host + '/api/u/pay/order'
export const URL_ORDER_LIST = host + '/api/u/order/list'
export const URL_ORDER_EXPRRESS_LIST = host + '/api/u/order/express/list'
export const URL_ORDER_EXPRRESS_INFO = host + '/api/u/order/express/info'
export const URL_DELIVERY_STOCK_LIST = host + '/api/u/delivery/stock/list'
export const URL_DELIVERY_CALULATE = host + '/api/u/delivery/calculate'
export const URL_DELIVERY_SUBMIT = host + '/api/u/delivery/submit'
export const URL_LEVEL_INFO = host + '/api/u/level/info'
export const URL_LEVEL_UPGRADE_CALULATE = host + '/api/u/level/upgrade/calculate'
export const URL_BANKCARD_PUBLIC_ACCOUT = host + '/api/u/bankcard/public/account'
export const URL_WALLET_BALANCE = host + '/api/u/wallet/balance'
export const URL_WALLET_STANDBY_LIST = host + '/api/u/wallet/balance/standby/list'
export const URL_WALLET_WITHDRAW_LIST = host + '/api/u/wallet/withdraw/list'
export const URL_WALLET_WITHDRAW_BASIC = host + '/api/u/wallet/withdraw/basic'
export const URL_WALLET_WITHDRAW_SUBMIT = host + '/api/u/wallet/withdraw/submit'
export const URL_WALLET_RECHARGE_LIST = host + '/api/u/wallet/recharge/list'
export const URL_WALLET_RECHARGE_BASIC = host + '/api/u/wallet/recharge/basic'
export const URL_WALLET_RECHARGE_UNDERLINE_SUBMIT = host + '/api/u/wallet/recharge/underline/submit'
export const URL_WALLER_RECHARGE_ONLINE_ORDER = host + '/api/u/wallet/recharge/online/order'
export const URL_PAY_BALANCE = host + '/api/u/pay/balance'
export const URL_BONUS_MARKET_LIST = host + '/api/u/bonus/market/info'
export const URL_BONUS_MARKET_LIST_DETAIL = host + '/api/u/bonus/market/detail/list'
export const URL_BONUS_DETAIL_LIST = host + '/api/u/bonus/detail/list'
export const URL_DELIVERY_BESEND_LIST = host + '/api/u/delivery/besend/list'
export const URL_DELIVERY_BERECEIVED_LIST = host + '/api/u/delivery/bereceived/list'
export const URL_DELIVERY_COMPLETE_LIST = host + '/api/u/delivery/complete/list'
export const URL_SUB_ORDER_BECONFIRMED_LIST = host + '/api/u/sub/order/beconfirmed/list'
export const URL_SUB_ORDER_COMPLETE_LIST = host + '/api/u/sub/order/complete/list'
export const URL_SUB_ORDER_FILL = host + '/api/u/sub/order/fill'
export const URL_ORDER_ALL_LIST = host + '/api/u/order/list'
export const URL_ORDER_BEPAYED_LIST = host + '/api/u/order/bepayed/list'
export const URL_ORDRR_BESEND_LIST = host + '/api/u/order/besend/list'
export const URL_ORDER_BERECEIVED_LIST = host + '/api/u/order/bereceived/list'
export const URL_ORDER_COMPLETE_LIST = host + '/api/u/order/complete/list'
export const URL_ORDER_EPRESS_LIST = host + '/api/u/order/express/list'
export const URL_ORDER_EXPRESS_INFO = host + '/api/u/order/express/info'
export const URL_ORDER_DETAIL = host + '/api/u/order/detail'
export const URL_DELIVERY_DETAIL = host + '/api/u/delivery/detail'
export const URL_SUB_ORDER_DETAIL = host + '/api/u/sub/order/detail'
export const URL_WX_SINGATURE = host + '/api/wx/signature'
export const URL_WX_PAY_SIGNATURE = host + '/api/wx/pay/signature'
export const URL_PAY_WX_PREPAY = host + '/api/u/pay/wx/prepay'
export const URL_WX_OPENID = host + '/api/wx/openid'
export const URL_WX_USER = host + '/api/wx/user'
export const URL_ORDER_CANCEL = host + '/api/u/order/cancel'
export const URL_ORDER_CONFIRM = host + '/api/u/order/confirm'
export const URL_DELIVERY_CONFIRM = host + '/api/u/delivery/confirm'
export const URL_PAY_ORDER_INFO = host + '/api/u/pay/order/info'
export const URL_SUB_ORDER_CONFIRM_SEND = host + '/api/u/sub/order/confirm/send'
export const URL_SUB_ORDER_GIVE_UP = host + '/api/u/sub/order/give/up'
export const URL_DELIVERY_PURCHASE_LIST = host + '/api/u/delivery/purchase/list'
export const URL_MEMBER_CENTER = host + '/api/u/member/center'
export const URL_STORE_BASIC = host + '/api/u/store/basic'
export const URL_STORE_NAME_UPDATE = host + '/api/u/store/name/update'
export const URL_STORE_ORDER_LIST = host + '/api/u/store/order/list'
export const URL_STORE_PRODUCT_COST_LIST = host + '/api/u/store/product/cost/list'
export const URL_PAY_CART_CALCULATE = host + '/api/u/pay/cart/calculate'
export const URL_PAY_CART_ORDER = host + '/api/u/pay/cart/order'
export const URL_AFTERSALE_LIST = host + '/api/u/aftersale/list'
export const URL_AFTERSALE_SUBMIT = host + '/api/u/aftersale/submit'
export const URL_AFTERSALE_DETAIL = host + '/api/u/aftersale/detail'
export const URL_AFTERSALE_EXPRESS_FILL = host + '/api/u/aftersale/express/fill'
export const URL_AFTERSALE_CANCEL = host + '/api/u/aftersale/cancel'
export const URL_AFTERSALE_TAKEOVER = host + '/api/u/aftersale/takeover'
export const URL_AFTERSALE_UPDATE = host + '/api/u/aftersale/update'
export const URL_GUIDE_CERT_CODE_GET = host + '/api/u/guide/cert/code/get'
export const URL_GUIDE_CERT_START = host + '/api/u/guide/cert/start'
export const URL_GUIDE_CERT_RESULT = host + '/api/u/guide/cert/result'
export const URL_GUIDE_CERT_GET = host + '/api/u/guide/cert/get'
export const URL_GUIDE_CERT_SUBMIT = host + '/api/u/guide/cert/submit'
export const URL_INVITE_VIP = host + '/api/u/invite/vip'
export const URL_INVITE_MEMBER_LIST = host + '/api/u/invite/member/list'
export const URL_INVITED_VIP = host + '/api/u/invited/vip'
export const URL_INVITED_VIP_CODE_GET = host + '/api/u/invited/vip/code/get'
export const URL_INVITED_VIP_SUBMIT = host + '/api/u/invited/vip/submit'
export const URL_INVITE_DIAMONDS = host + '/api/u/invite/diamonds'
export const URL_INVITED_DIAMONDS = host + '/api/u/invited/diamonds'
export const URL_INVITED_DIAMONDS_CODE_GET = host + '/api/u/invited/diamonds/code/get'
export const URL_INVITED_DIAMONDS_ORDER = host + '/api/u/invited/diamonds/order'
export const URL_UPGRADE_DIAMONDS_CODE_GET = host + '/api/u/upgrade/diamonds/code/get'
export const URL_UPGRADE_DIAMONDS_ORDER = host + '/api/u/upgrade/diamonds/order'
export const URL_MEMBER_DIAMONDS_GOODS_LIST = host + '/api/u/member/diamonds/goods/list'
export const URL_MEMBER_DIAMONDS_EXCHANGE_ORDER = host + '/api/u/upgrade/diamonds/exchange/order'
export const URL_TOURLIST_START_CITY_LIST = host + '/api/u/tourist/start/city/list'
export const URL_TOURLIST_TO_PROVINCE_LIST = host + '/api/u/tourist/to/province/list'
export const URL_TOURLIST_ADDRESS_LIST = host + '/api/u/tourist/address/list'
export const URL_TOURLIST_SERVICE_LIST = host + '/api/u/tourist/service/list'
export const URL_TOURLIST_GOODS_LIST = host + '/api/u/tourist/goods/list'
export const URL_TOURLIST_DETAIL = host + '/api/u/tourist/detail'
export const URL_TOURLIST_COMPLETE_LIST = host + '/api/u/tourist/complete/list'
export const URL_TOURLIST_SUBMIT = host + '/api/u/tourist/submit'
export const URL_TOURLIST_CANCEL = host + '/api/u/tourist/cancel'
export const URL_TOURLIST_START_CONFIRM = host + '/api/u/tourist/start/confirm'
export const URL_TOURLIST_ORDER_BESEND_LIST = host + '/api/u/tourist/order/besend/list'
export const URL_TOURLIST_ORDER_COMPLETE_LIST = host + '/api/u/tourist/order/complete/list'
export const URL_TOURLIST_ORDER_CANCEL = host + '/api/u/tourist/order/cancel'
export const URL_TOURLIST_ORDER_COMPLETE = host + '/api/u/tourist/order/complete'
export const URL_TOURLIST_START_AGENCY_LIST = host + '/api/u/tourist/start/agency/list'
export const URL_ASSIST_SHARE_DEFAULT = host + '/api/u/assist/share/default'

export const URL_DATA_GOODS_LOAD = host + '/data/goods/load'



