let host = ''
if (process.env.NODE_ENV !== 'production'){
  host = 'https://mall-api.malrro.com'
}else {
  if (process.env.type == 'test'){
    host = 'https://mall-api.malrro.com'
  }else {
    host = 'https://mall-api.malrro.com'
  }
}

//请求的所有url地址
export const URL_GET_LOGIN_CODE = host + '/api/u/auth/login/code/get'
export const URL_GET_LOGIN_BY_PHONE = host + '/api/u/auth/code/login'
export const URL_GET_LOGIN_BY_PASSWORD = host + '/api/u/auth/password/login'
export const URL_GET_LOGIN_OUT = host + '/api/u/auth/logout'
export const URL_SET_PAY_PASSWORD = host + '/api/u/password/pay/set'
export const URL_GET_PAY_CODE = host + '/api/u/password/pay/code/get'
export const URL_GET_PAY_VALIDATE_CODE = host + '/api/u/password/pay/code/validate'
export const URL_UPDATE_PAY = host + '/api/u/password/pay/update'
export const URL_SET_LOGIN_PASSWORD = host + '/api/u/password/login/set'
export const URL_FORGOT_PARRWORD = host + '/api/u/password/forgot/code/get'
export const URL_FORGOT_VALIDATE_CODE = host + '/api/u/password/forgot/code/validate'
export const URL_PASSWORD_FORGOT_RESET = host + '/api/u/password/forgot/reset'
export const URL_GET_SHOP_LIST = host + '/api/u/shop/index'
export const URL_MEMBER_REGISTER_INFO = host + '/api/u/member/register/info'
export const URL_MEMBER_REGISTER_CODE = host + '/api/u/member/register/code/get'
export const URL_MEMBER_REGISTER_SUBMIT = host + '/api/u/member/register/submit'
export const URL_FILE_BASE64_UPLOAD = host + '/api/u/file/base64/upload'
export const URL_FILE_FORMDATA_UPLOAD = host + '/api/u/file/upload'
export const URL_DATA_CONFIG_BIZPARAM = host + '/data/config/bizparam'
export const URL_MEMBER_ASSIST_REGISTER_INFO = host + '/api/u/member/assist/register/info'
export const URL_MEMBER_ASSIST_REGISTER_CODE = host + '/api/u/member/assist/register/code/get'
export const URL_MEMBER_ASSIST_REGISTER_SUBMIT = host + '/api/u/member/assist/register/submit'
export const URL_MEMBER_INFO = host + '/api/u/member/info'
export const URL_MEMBER_NICKNAME_SET = host + '/api/u/member/nickname/set'
export const URL_MEMBER_SEX_SET = host + '/api/u/member/sex/set'
export const URL_MEMBER_BIRTHDAY_SET = host + '/api/u/member/birthday/set'
export const URL_MEMBER_AVATAR_SET = host + '/api/u/member/avatar/set'
export const URL_MEMBER_PHONE_MOD_CODE = host + '/api/u/member/phone/mod/code/get'
export const URL_MEMBER_PHONE_MOD_VALIDATE = host + '/api/u/member/phone/mod/code/validate'
export const URL_MEMBER_PHONE_NEW_CODE = host + '/api/u/member/phone/new/code/get'
export const URL_MEMBER_PHONE_NEW_SET = host + '/api/u/member/phone/new/set'
export const URL_BANKCARD_LIST = host + '/api/u/bankcard/list'
export const URL_BANKCARD_DEFAULT_SET = host + '/api/u/bankcard/default/set'
export const URL_BANKCARD_RECOGNISE = host + '/api/u/bankcard/recognise'
export const URL_BANKCARD_ADD = host + '/api/u/bankcard/add'
export const URL_BANKCARD_DEL = host + '/api/u/bankcard/del'
export const URL_BANKCARD_SUPPORT_LIST = host + '/api/u/bankcard/support/list'
export const URL_BANKCARD_DEFAULT_WIYHDRAW_GET = host + '/api/u/bankcard/default/withdraw/get'
export const URL_BANKCARD_DEFAULT_WIYHDRAW_BASIC = host + '/api/u/wallet/withdraw/basic'
export const URL_BANKCARD_DEBIT_LIST = host + '/api/u/bankcard/debit/list'
export const URL_COLLECT_LIST = host + '/api/u/collect/list'
export const URL_COLLECT_ADD = host + '/api/u/collect/add'
export const URL_COLLECT_CENCEL = host + '/api/u/collect/cancel'
export const URL_ADDRESS_LIST = host + '/api/u/address/list'
export const URL_ADDRESS_SAVE = host + '/api/u/address/save'
export const URL_ADDRESS_DEL = host + '/api/u/address/del'
export const URL_ASSIST_POSTER = host + '/api/u/assist/poster'
export const URL_ASSIST_FEEDBACK_ADD = host + '/api/u/assist/feedback/add'
export const URL_ASSIST_MSG_LIST = host + '/api/u/assist/msg/list'
export const URL_ASSIST_PEOPLE_DIRECT = host + '/api/u/assist/people/direct'
export const URL_GOODS_CATEGORY_LIST = host + '/api/u/shop/goods/category/list'
export const URL_SHOP_GOODS_LIST = host + '/api/u/shop/goods/list'
export const URL_GOODS_GIFT_LIST = host + '/api/u/shop/gift/package/detail'
export const URL_SHOP_GOODS_DETAIL = host + '/api/u/shop/goods/detail'
export const URL_SHOP_MARKET_PACKAGE_LIST = host + '/api/u/shop/market/package/list'
export const URL_PACKAGE_CATEGORY_LIST = host + '/api/u/shop/market/package/detail'
export const URL_CART_LIST = host + '/api/u/cart/list'
export const URL_CART_PLUS = host + '/api/u/cart/plus'
export const URL_CART_REDUCE = host + '/api/u/cart/reduce'
export const URL_CART_REMOVE = host + '/api/u/cart/remove'
export const URL_PAY_CALCULATE = host + '/api/u/pay/calculate'
export const URL_PAY_ORDER = host + '/api/u/pay/order'
export const URL_ORDER_LIST = host + '/api/u/order/list'
export const URL_ORDER_EXPRRESS_LIST = host + '/api/u/order/express/list'
export const URL_ORDER_EXPRRESS_INFO = host + '/api/u/order/express/info'
export const URL_DELIVERY_STOCK_LIST = host + '/api/u/delivery/stock/list'
export const URL_DELIVERY_CALULATE = host + '/api/u/delivery/calculate'
export const URL_DELIVERY_SUBMIT = host + '/api/u/delivery/submit'
export const URL_LEVEL_INFO = host + '/api/u/level/info'
export const URL_LEVEL_UPGRADE_CALULATE = host + '/api/u/level/upgrade/calculate'
export const URL_BANKCARD_PUBLIC_ACCOUT = host + '/api/u/bankcard/public/account'
export const URL_WALLET_BALANCE = host + '/api/u/wallet/balance'
export const URL_WALLET_WITHDRAW_LIST = host + '/api/u/wallet/withdraw/list'
export const URL_WALLET_WITHDRAW_BASIC = host + '/api/u/wallet/withdraw/basic'
export const URL_WALLET_WITHDRAW_SUBMIT = host + '/api/u/wallet/withdraw/submit'
export const URL_WALLET_RECHARGE_LIST = host + '/api/u/wallet/recharge/list'
export const URL_WALLET_RECHARGE_BASIC = host + '/api/u/wallet/recharge/basic'
export const URL_WALLET_RECHARGE_UNDERLINE_SUBMIT = host + '/api/u/wallet/recharge/underline/submit'
export const URL_WALLER_RECHARGE_ONLINE_ORDER = host + '/api/u/wallet/recharge/online/order'
export const URL_PAY_BALANCE = host + '/api/u/pay/balance'
export const URL_BONUS_MARKET_LIST = host + '/api/u/bonus/market/info'
export const URL_BONUS_MARKET_LIST_DETAIL = host + '/api/u/bonus/market/detail/list'
export const URL_BONUS_DETAIL_LIST = host + '/api/u/bonus/detail/list'
export const URL_DELIVERY_BESEND_LIST = host + '/api/u/delivery/besend/list'
export const URL_DELIVERY_BERECEIVED_LIST = host + '/api/u/delivery/bereceived/list'
export const URL_DELIVERY_COMPLETE_LIST = host + '/api/u/delivery/complete/list'
export const URL_SUB_ORDER_BECONFIRMED_LIST = host + '/api/u/sub/order/beconfirmed/list'
export const URL_SUB_ORDER_COMPLETE_LIST = host + '/api/u/sub/order/complete/list'
export const URL_SUB_ORDER_FILL = host + '/api/u/sub/order/fill'
export const URL_ORDER_ALL_LIST = host + '/api/u/order/list'
export const URL_ORDER_BEPAYED_LIST = host + '/api/u/order/bepayed/list'
export const URL_ORDRR_BESEND_LIST = host + '/api/u/order/besend/list'
export const URL_ORDER_BERECEIVED_LIST = host + '/api/u/order/bereceived/list'
export const URL_ORDER_COMPLETE_LIST = host + '/api/u/order/complete/list'
export const URL_ORDER_EPRESS_LIST = host + '/api/u/order/express/list'
export const URL_ORDER_EXPRESS_INFO = host + '/api/u/order/express/info'
export const URL_ORDER_DETAIL = host + '/api/u/order/detail'
export const URL_DELIVERY_DETAIL = host + '/api/u/delivery/detail'
export const URL_SUB_ORDER_DETAIL = host + '/api/u/sub/order/detail'
export const URL_WX_SINGATURE = host + '/api/wx/signature'
export const URL_WX_PAY_SIGNATURE = host + '/api/wx/pay/signature'
export const URL_PAY_WX_PREPAY = host + '/api/u/pay/wx/prepay'
export const URL_WX_OPENID = host + '/api/wx/openid'
export const URL_ORDER_CANCEL = host + '/api/u/order/cancel'
export const URL_ORDER_CONFIRM = host + '/api/u/order/confirm'
export const URL_DELIVERY_CONFIRM = host + '/api/u/delivery/confirm'
export const URL_PAY_ORDER_INFO = host + '/api/u/pay/order/info'
export const URL_SUB_ORDER_CONFIRM_SEND = host + '/api/u/sub/order/confirm/send'
export const URL_SUB_ORDER_GIVE_UP = host + '/api/u/sub/order/give/up'
export const URL_AFTERSALE_LIST = host + '/api/u/aftersale/list'
export const URL_DELIVERY_PURCHASE_LIST = host + '/api/u/delivery/purchase/list'
export const URL_MEMBER_CENTER = host + '/api/u/member/center'



export const URL_DATA_GOODS_LOAD = host + '/data/goods/load'



